### ISSUE TITLE
Inconsistent Order of Errors?

### ISSUE THREAD

**Issue by jonmchan** [go-playground/validator#260]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:

Is there any way to make validator return errors in a consistent order or sort the validation errors? I'm trying to write a test against 3 errors, but the test fails randomly when the order of the errors are returned in different orders each time the test is run.

### Code sample, to showcase or reproduce:

```go
type TestStruct struct {
	Name string `binding:"required,alpha"`
	Age string `binding:"number"`
	Zipcode string `binding:"len=5"`
}

func TestHandleValidationError(t *testing.T) {
	var testData = TestStruct{"Jonny5", "sadf", "1"}
	err := binding.Validator.ValidateStruct(testData)

	fmt.Println(err.(validator.ValidationErrors).Error())
	return
}
```
Return Value Run 1:
```
Key: 'TestStruct.Zipcode' Error:Field validation for 'Zipcode' failed on the 'len' tag

Key: 'TestStruct.Name' Error:Field validation for 'Name' failed on the 'alpha' tag

Key: 'TestStruct.Age' Error:Field validation for 'Age' failed on the 'number' tag
```

Return Value Run 2:
```
Key: 'TestStruct.Name' Error:Field validation for 'Name' failed on the 'alpha' tag

Key: 'TestStruct.Age' Error:Field validation for 'Age' failed on the 'number' tag

Key: 'TestStruct.Zipcode' Error:Field validation for 'Zipcode' failed on the 'len' tag
```

**Comment by joeybloggs** [comment]
Hey @jonmchan 

That is very strange, the errors returned in v9 are in an array and validator is synchronous, so they should always return in the same order.

I will investigate, if you could provide your full test code that would be helpful, just to rule out the reuse of a variable or something.

**Comment by joeybloggs** [comment]
@jonmchan update,

found the issue, I was storing the field cache in a map (for some reason) converting to an array now; should be fixed within a few hours at most :)

thanks for reporting

**Comment by joeybloggs** [comment]
Hey @jonmchan 

I've made the appropriate changes in [release 9.2.2](https://github.com/go-playground/validator/releases/tag/v9.2.2), please confirm this solves this for you :)

**Comment by jonmchan** [comment]
@joeybloggs - you work fast! Yes, I updated my gin validator to v9. I'll test release 9.2.2 tomorrow and close this bug if I can confirm that the order of errors remain static. Thanks!

**Comment by jonmchan** [comment]
The test assertions pass everytime! That did the trick! Thanks!
