### ISSUE TITLE
required_without does not work with pointers

### ISSUE THREAD

**Issue by tbe** [go-playground/validator#483]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
`required_without` does not work with pointers

### Code sample, to showcase or reproduce:

Playground: https://play.golang.org/p/5hpXOfDJU4V
```go
package main

import (
	"fmt"
	"gopkg.in/go-playground/validator.v9"
)

type a struct {
	Field1 *string `validate:"required_without=Field2"`
	Field2 *int    `validate:"required_without=Field1"`
}

func main() {
	validate := validator.New()

	testStr := new(string)
	*testStr = "abcd"

	testInt := new(int)
	*testInt = 42

	if err := validate.Struct(a{Field1: testStr}); err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("Test A OK")
	}

	if err := validate.Struct(a{Field2: testInt}); err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("Test B OK")
	}

	if err := validate.Struct(a{Field1: testStr, Field2: testInt}); err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("Test C OK")
	}
}
```

**Comment by AlexanderGrom** [comment]
Hello!
https://play.golang.org/p/lx1Qoi1HLOF
```
package main

import (
	"fmt"
	"gopkg.in/go-playground/validator.v9"
)

type a struct {
	Field1 string `validate:"required_with=Field2"`
	Field2 int    `validate:"required_with=Field1"`
}

func main() {
	validate := validator.New()

	// req is a pointer!
	req := &a{
		Field1: "string",
	}

	defer func() {
		if r := recover(); r != nil {
			fmt.Println("Recovered:", r)
		}
	}()

	// We get panic! (req is a pointer)
	if err := validate.Struct(req); err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("Test A OK")
	}

	if err := validate.Struct(*req); err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("Test B OK")
	}
}
```

I get panic: `reflect: call of reflect.Value.FieldByName on ptr Value`

`fl.Parent().Kind()` is a pointer if struct is a pointer.

Usually in http frameworks the request is a pointer.
```
var request = new(myRequest)
if err = ctx.BindJSON(request); err != nil {
	c.BadRequestError(ctx, "bad_request")
	return
}
```

**Comment by crathjen** [comment]
@tbe did https://github.com/go-playground/validator/pull/484 fix your issue?  Because I still seem to be experiencing the problem that you identified (seeing it on the `required_without_all` tag rather than `required_with`).   
Another example: https://play.golang.org/p/Gx6hh4ASKQa

```go
package main

import (
	"gopkg.in/go-playground/validator.v9"
	"fmt"
)

func main() {
	
	v:=validator.New()
	
	result := v.Struct(foo{A: &emptystruct{}})
	if result != nil {
		fmt.Println(fmt.Sprintf("Unexpected Error: %s", result))
	}
	
	result = v.Struct(bar{A: "somevalue"})
	if result != nil {
		fmt.Println(fmt.Sprintf("Unexpected Error: %s", result))
	}
	
}

type foo struct {
	A *emptystruct `validate:"required"`
	B *emptystruct `validate:"required_without_all=A C"`
	C *emptystruct
}

type bar struct {
	A string `validate:"required"`
	B string `validate:"required_without_all=A C"`
	C string
}

type emptystruct struct {
}
```
gives the error 
```
Unexpected Error: Key: 'foo.B' Error:Field validation for 'B' failed on the 'required_without_all' tag
```
The fact that this does not also output a failure for `foo.A` being required highlights the discrepancy between the behavior of `required` and the behavior of `required_without_all`

**Comment by johndww** [comment]
@leafduo @crathjen @tbe I don't think the fixed worked either.
```
func TestLookup(t *testing.T) {
	type Lookup struct {
		FieldA *string `json:"fieldA,omitempty" validate:"required_without=FieldB"`
		FieldB *string `json:"fieldB,omitempty" validate:"required_without=FieldA"`
	}

	fieldAValue := "1232"
	lookup := Lookup{
		FieldA: &fieldAValue,
		FieldB: nil,
	}

	assert.NoError(t, validator.New().Struct(lookup))
}
```
fails on 9.29.1

**Comment by renxiawang** [comment]
@johndww +1, still failing on 9.29.1.

**Comment by deankarn** [comment]
sorry that I have not been able to take a look at this, super busy with work right now.

If anyone can help with the debugging and a PR it would be very appreciated :)

**Comment by leafduo** [comment]
#484 fixed panicking when the variable to validate is pointer, as in https://github.com/go-playground/validator/blob/v9/validator_test.go#L8715.

But it did not fix the problem of `required_without` working with pointers. Digging into the code, I've found out that the problem is in `traverseField`:

https://github.com/go-playground/validator/blob/556b9da3c05f2a935bc086fb5a0bb55dd8112d2d/validator.go#L96-L159
```
// traverseField validates any field, be it a struct or single field, ensures it's validity and passes it along to be validated via it's tag options
func (v *validate) traverseField(ctx context.Context, parent reflect.Value, current reflect.Value, ns []byte, structNs []byte, cf *cField, ct *cTag) {

	var typ reflect.Type
	var kind reflect.Kind

	current, kind, v.fldIsPointer = v.extractTypeInternal(current, false)

	switch kind {
	case reflect.Ptr, reflect.Interface, reflect.Invalid:

		if ct == nil {
			return
		}

		if ct.typeof == typeOmitEmpty || ct.typeof == typeIsDefault {
			return
		}

		if ct.hasTag {
//...
			v.errs = append(v.errs,
				&fieldError{
					v:              v.v,
					tag:            ct.aliasTag,
					actualTag:      ct.tag,
					ns:             v.str1,
					structNs:       v.str2,
					fieldLen:       uint8(len(cf.altName)),
					structfieldLen: uint8(len(cf.name)),
					value:          current.Interface(),
					param:          ct.param,
					kind:           kind,
					typ:            current.Type(),
				},
			)

			return
		}
//...
```

According to code above, any pointer with validator other than `omitempty` or `isdefault` and has tag will throw error. Although I've found the bad code path, I don't know how to fix it, because I don't fully understand the logic. For example, how does other validators work with pointers? What does `hasTag` mean?

@deankarn can you shed some light?

BTW, in the test code, `if errs != nil` is misspelled as `if errs == nil` at https://github.com/go-playground/validator/blob/556b9da3c05f2a935bc086fb5a0bb55dd8112d2d/validator_test.go#L8717 and https://github.com/go-playground/validator/blob/556b9da3c05f2a935bc086fb5a0bb55dd8112d2d/validator_test.go#L8762, which causes the bug not to be found.

**Comment by leafduo** [comment]
Maybe https://github.com/go-playground/validator/pull/510 will fix this issue?

**Comment by deankarn** [comment]
For context how other validations work with pointers is that they are dereferenced prior to validation, but since the value is nil then there's nothing to dereference.

I think another exception may be necessary like `omitempty` and `isdefault`.

I like #510 but it's unfortunately a breaking change.

**Comment by deankarn** [comment]
I released a bunch of fixes today including all `required_with*` functionality, please let me know if this works as expected for you now, see [v9.30.0](https://github.com/go-playground/validator/releases/tag/v9.30.0)

**Comment by renxiawang** [comment]
So with the latest version, the issue is not fully resolved. 
Working code: https://play.golang.org/p/PPp8OeT-2xG
Not working code: https://play.golang.org/p/scNTDSb_r4c (assigning false to a *bool breaks)

**Comment by talmr** [comment]
@deankarn Similarly to @renxiawang  pointer to float64 also does not work when using `required_with`

**Comment by deankarn** [comment]
I believe I've properly corrected the issues now and released in:

- https://github.com/go-playground/validator/releases/tag/v9.30.1
- https://github.com/go-playground/validator/releases/tag/v10.0.1

P.S. I highly recomment updating to **v10**

**Comment by melonaerial** [comment]
Hello @deankarn 
Do you ave any plans to add `one_of` functionality for required? For example, if I want to that just one of `Field1` and `Field2` was set, I have to write code something like this https://play.golang.org/p/tY4x6H5h8io . But this not so good hack I think. Or write required validation by my function.

**Comment by deankarn** [comment]
@melonaerial can you please open a new issue next time 🙏 it's hard discussing in a closed and unrelated thread.

I'm not 100% sure what you're trying to accomplish? doesn't `required_without_all` suite your use case?

**Comment by MaciejKaras** [comment]
Hi @deankarn 

I'm not sure it works when you have mulitple validation tags. Please run:
https://play.golang.org/p/Aq1ebMyzXs8
